### ISSUE TITLE
Roundy touch event not working on IOS 13 (ipad)

### ISSUE THREAD

**Issue by arch-stefanozanetti** [themre/roundy#18] opened 2020-01-30 15:39 UTC
Is there a way to let Roundy work evend on IOS 13 on Ipad?

**Comment by themre** [comment] 2020-01-31 07:32
hi, i don't have Ipad with me. i will try to get some and see what is going on. do you have some errors or what currently happens?

**Comment by arch-stefanozanetti** [comment] 2020-01-31 08:38
Actually I think it's a safari problem because it works on iPad chrome
browser.

I didn't receive any errors but, even the codesandbox demo doesn't work.


Thank you


Il ven 31 gen 2020, 08:32 Marko Trebizan <notifications@github.com> ha
scritto:

**Comment by mrzarkovic** [comment] 2020-03-05 10:53
Any progress on this one? I'm also having this issue.
Otherwise, this is a great library! Keep up the good work.

**Comment by themre** [comment] 2020-03-06 13:57
hey, sorry that this is not fixed yet, but lately i've been occupied a lot at work. i can't promise when i will have the chance to take a look at it :(

**Comment by themre** [comment] 2020-03-15 09:38
Hey, after a while i started working again on this library. I used https://github.com/jaredpalmer/tsdx to develop everything with Typescript. And to get past various dragging issues I also used https://github.com/react-spring/react-use-gesture. Everything is rewritten in hooks. There are probably some issue still, but for now I would like to ask you if you could test this with `yarn add roundy@next`. Demo is also here: https://codesandbox.io/s/vibrant-swanson-9zu9d

**Comment by themre** [comment] 2020-03-27 19:57
I published new version, 3.x. It's a breaking change since it relies on hooks (> React 16.8). I tested on iPad and it works, but would ask if you can test it if there are some other issues. I will close this issue and if new one occurs, please file new bug. Thanks!

**Closed by themre** 2020-03-27 19:57 UTC

**Comment by mrzarkovic** [comment] 2020-03-31 12:13
@themre I can confirm from my side that the issue is fixed! Thanks!
